### Testing Grounds

In [1]:
print("This is a testing Ground")

This is a testing Ground

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("APIs\shatta_wale_data\shatta_wale_data_20260322.csv")

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1265 entries, 0 to 1264
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          1265 non-null   object
 1   release_date   1265 non-null   object
 2   producer       1265 non-null   object
 3   genre          1265 non-null   object
 4   duration       1265 non-null   object
 5   comment_count  1265 non-null   int64
 6   like_count     1265 non-null   int64
 7   view_count     1265 non-null   int64
 8   video_url      1265 non-null   object
 9   description    1144 non-null   object
 10  audio          1265 non-null   bool
 11  is_single      1265 non-null   bool
 12  video_id       1265 non-null   object
dtypes: bool(2), int64(3), object(8)
memory usage: 111.3+ KB

In [3]:
pd.read_csv("APIs\shatta_wale_data\lastfm_tracks_20260322_140603.csv")

,track_name,track_playcount,track_listeners,track_url,track_rank,album_name
0,Hossana,7528,1494,https://www.last.fm/music/SHATTA+WALE/_/Hossana,1,NaN
1,Hol' It,6610,1481,https://www.last.fm/music/SHATTA+WALE/_/Hol%27+It,2,NaN
2,Baby (Chop Kiss),5618,1437,https://www.last.fm/music/SHATTA+WALE/_/Baby+(...,3,NaN
3,Dancehall King,6309,1348,https://www.last.fm/music/SHATTA+WALE/_/Danceh...,4,NaN
4,Ayoo,6917,1284,https://www.last.fm/music/SHATTA+WALE/_/Ayoo,5,NaN
...,...,...,...,...,...,...
95,My Mind Is Made Up,195,77,https://www.last.fm/music/SHATTA+WALE/_/My+Min...,96,NaN
96,STREET CROWN,6361,76,https://www.last.fm/music/SHATTA+WALE/_/STREET...,97,NaN
97,"So Real, So Me",2171,76,https://www.last.fm/music/SHATTA+WALE/_/So+Rea...,98,NaN
98,KING IN A LIFE. (African Dancehall),843,73,https://www.last.fm/music/SHATTA+WALE/_/KING+I...,99,NaN
99,If I Collect,178,73,https://www.last.fm/music/SHATTA+WALE/_/If+I+C...,100,NaN

In [7]:
pd.read_csv("APIs\shatta_wale_data\itunes_tracks_20260322_203158.csv")

,track_name,artist_name,album_name,release_date,release_year,duration_seconds,track_number,disc_number,genre,explicit,track_price,itunes_url,preview_url,artwork_url,track_id
0,AIN'T NOBODY (feat. JOHN LEGEND),Shatta Wale,AIN'T NOBODY (feat. JOHN LEGEND) - Single,2026-03-20T12:00:00Z,2026,202.036,1,1,Reggae,False,0.99,https://music.apple.com/us/album/aint-nobody-f...,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,1884846157
1,Yawa Ni (shatta music),Shatta Wale,The Interface (Shatta Music Genre),2026-02-19T12:00:00Z,2026,151.288,6,1,Afro-Pop,False,1.29,https://music.apple.com/us/album/yawa-ni-shatt...,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,1879112174
2,Danger,Shatta Wale,Danger - Single,2026-02-16T12:00:00Z,2026,140.109,1,1,Modern Dancehall,True,1.29,https://music.apple.com/us/album/danger/187648...,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,1876487402
3,Big Lie Dat,Shatta Wale,Big Lie Dat - Single,2026-02-13T12:00:00Z,2026,138.469,1,1,Reggae,True,1.29,https://music.apple.com/us/album/big-lie-dat/1...,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,1875329291
4,Rise Anyway,Shatta Wale,Echoes Of The Ghetto (African Dancehall) - EP,2026-01-15T12:00:00Z,2026,149.442,2,1,Reggae,False,1.29,https://music.apple.com/us/album/rise-anyway/1...,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,1868946926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Pinga (feat. Shatta Wale),DJ Breezy,Pinga (feat. Shatta Wale) - Single,2014-08-04T12:00:00Z,2014,190.202,1,1,Hip-Hop/Rap,False,0.00,https://music.apple.com/us/album/pinga-feat-sh...,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,905956380
196,Everybody Like My Ting,Shatta Wale,Answers (The Hybrid),2014-03-14T12:00:00Z,2014,159.335,33,1,Reggae,True,1.29,https://music.apple.com/us/album/everybody-lik...,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,1808920512
197,Enter the Net,Shatta Wale,Answers (The Hybrid),2014-03-14T12:00:00Z,2014,202.106,5,1,Reggae,True,1.29,https://music.apple.com/us/album/enter-the-net...,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,1808920332
198,Shatta City,Shatta Wale,Up a Road Mixtape,2013-03-01T12:00:00Z,2013,165.442,10,1,Modern Dancehall,False,1.29,https://music.apple.com/us/album/shatta-city/1...,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,1806113784
199,Baby (Chop Kiss),Shatta Wale,Baby (Chop Kiss) - Single,2004-01-01T12:00:00Z,2004,198.973,1,1,Afro-Beat,False,1.29,https://music.apple.com/us/album/baby-chop-kis...,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...,1818849338

In [1]:
from soundcloud import SoundCloudClient

ModuleNotFoundError: No module named 'soundcloud'

In [8]:
import pandas as pd
df = pd.read_csv("CSV_files\csv_files_utf8\songs_fact.csv", encoding="UTF8")

In [9]:
print("Total rows:", len(df))
print("\nRows with NULL/NaN song_id:", df['song_id'].isna().sum())
print("Rows with empty string song_id:", (df['song_id'] == '').sum())
print("Rows with 'null' as string:", (df['song_id'] == 'null').sum())
print("\nFirst 10 song_id values:")
print(df['song_id'].head(10))
print("\nData types:", df['song_id'].dtype)

Total rows: 1027

Rows with NULL/NaN song_id: 58
Rows with empty string song_id: 0
Rows with 'null' as string: 0

First 10 song_id values:
0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
Name: song_id, dtype: float64

Data types: float64

In [12]:
df[960:1027]

,song_id,project_id,title,artiste_name,audio,video,release_date,producers,genre,duration,notes
960,961.0,1.0,It'S Not Over (Mix Masta Garzy Remix),Shatta Wale,True,False,14/02/2017,NaN,Reggae,03:48,NaN
961,962.0,1.0,Jeje (Feat. Shatta Wale),Sista Afia,True,False,20/12/2016,NaN,Worldwide,03:39,NaN
962,963.0,1.0,Party Fi Life (Feat. Shatta Wale),Shawn Storm,True,False,09/09/2016,NaN,Reggae,02:42,NaN
963,964.0,1.0,Too Big (Feat. Shatta Wale),Maccasio,True,False,05/08/2016,NaN,Afro-Beat,04:08,NaN
964,965.0,1.0,Atm Remix (Feat. Shatta Wale),Alkaline,True,False,27/05/2016,NaN,Reggae,03:39,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN